# Generated by Django 5.1 on 2024-08-21 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('autor', models.CharField(max_length=256)),
                ('paginas', models.IntegerField()),
                ('descricao', models.TextField()),
                ('dataPublicacao', models.DateField()),
                ('editora', models.CharField(max_length=256)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
