# Generated by Django 5.1 on 2024-09-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_livro_options_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='seguindo',
            field=models.ManyToManyField(blank=True, to='api.perfil'),
        ),
    ]
