# Generated by Django 5.1 on 2024-09-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_perfil_seguindo'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='condicao',
            field=models.CharField(choices=[('novo', 'Novo'), ('seminovo', 'Seminovo'), ('usado', 'Usado')], default='usado', max_length=10),
        ),
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.CharField(default=57, max_length=256),
            preserve_default=False,
        ),
    ]
