# Generated by Django 5.1 on 2024-10-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_livro_atualizado_em_livro_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='resenha',
            field=models.TextField(blank=True, null=True),
        ),
    ]
