# Generated by Django 5.1 on 2024-10-14 16:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_livro_resenha'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='curtidas',
            field=models.ManyToManyField(blank=True, related_name='livros_curtidos', to='api.perfil'),
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='api.perfil')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='api.livro')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
            },
        ),
    ]
