# Generated by Django 5.1 on 2024-10-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_livro_curtidas_comentarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
