# Generated by Django 5.1 on 2024-10-31 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='disponibilidade',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='pontuacao',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Troca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('recusada', 'Recusada')], max_length=20)),
                ('avaliacao', models.PositiveIntegerField(blank=True, null=True)),
                ('pontuacao', models.PositiveIntegerField(default=0)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_recebidas', to='api.perfil')),
                ('livro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.livro')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_solicitadas', to='api.perfil')),
            ],
        ),
    ]
