# Generated by Django 5.1 on 2024-10-31 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_livro_disponibilidade_perfil_pontuacao_troca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='pontuacao',
            new_name='pontuacao_total',
        ),
    ]
