# Generated by Django 5.1 on 2024-11-03 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_chat_chatmessages_chatrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='livro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.livro', verbose_name='Livro Solicitado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
