# Generated by Django 5.1 on 2024-11-03 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_pontuacao_perfil_pontuacao_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='troca',
            options={'verbose_name': 'Troca', 'verbose_name_plural': 'Trocas'},
        ),
        migrations.RenameField(
            model_name='troca',
            old_name='avaliacao',
            new_name='avaliacao_recebedor',
        ),
        migrations.RenameField(
            model_name='troca',
            old_name='data',
            new_name='data_troca',
        ),
        migrations.RenameField(
            model_name='troca',
            old_name='destinatario',
            new_name='recebedor',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='pontuacao_total',
        ),
        migrations.RemoveField(
            model_name='troca',
            name='pontuacao',
        ),
        migrations.AddField(
            model_name='livro',
            name='media_avaliacoes',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='livro',
            name='total_avaliacoes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='pontuacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='troca',
            name='avaliacao_solicitante',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='troca',
            name='avaliado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='troca',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livro'),
        ),
        migrations.AlterField(
            model_name='troca',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], default='Pendente', max_length=20),
        ),
    ]
