# Generated by Django 5.1 on 2024-11-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_chat_chatmessages_chatrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='trocaFeita',
            field=models.BooleanField(default=False, verbose_name='Troca foi realizada?'),
        ),
        migrations.DeleteModel(
            name='Troca',
        ),
    ]
